var jq=$.noConflict(),gtags={},prot,prots=[],labels={},Hval="",Hcols=64,Hrows=1,Loaded=0;
jq(document).ready(function(){jq.get("./.tags.csv",function(a){for(a=a.split("\n");l=a.shift();)8<l.length&&(v=l.split(";"),v[0]&&v[1]&&(labels[myTrim(v[0])]=myTrim(v[1])))});jq.getJSON("./.json",function(a){jq.each(a.p,function(a,c){addP(c)});addT()});jq("a.c_ab").click(function(){ab(this)});initY();getD(jq("#yaml"));jq(window).resize(function(){var a=jq(window).width();jq("#yaml").width(a-30)});jq(window).resize();jq("input#submit").click(function(){var a=jq("textarea#hex").val();1==a.length%2&&
(a+="F");jq.post("/lib/",{p:prot.path,n:jq("#tools a.c_b").text(),I:"fromstring",N:"unpack",O:"toyaml_html",str:a},function(a,c){"success"==c&&initY(a)})});jq("input#line").show(updH());jq.fn.getC=function(){var a=jq(this).get(0),b=0;if("selectionStart"in a)b=a.selectionStart;else if("selection"in document){a.focus();var b=document.selection.createRange(),c=document.selection.createRange().text.length;b.moveStart("character",-a.value.length);b=b.text.length-c}return b};jq.fn.setC=function(a,b){b||
(b=a);return this.each(function(){if(this.setSelectionRange)this.focus(),this.setSelectionRange(a,b);else if(this.createTextRange){var c=this.createTextRange();c.collapse(!0);c.moveEnd("character",b);c.moveStart("character",a);c.select()}})};jq("textarea#hex").on("change keyup paste",function(){var a=jq(this),b=a.val();if(b!=Hval){var c=a.getC(),d=b.substr(0,c),b=b.substr(c,b.length),d=d.replace(/[^0-9A-F]/gi,""),b=b.replace(/[^0-9A-F]/gi,"");Hval=d+b;a.val(Hval);a.setC(d.length);Hrows=Math.ceil(Hval.length/
Hcols);0<Hval.length-Hrows*Hcols&&Hrows++;updH()}});updH()});jq(document).keydown(function(a){a.altKey&&(73==a.keyCode&&jq("a.c_ab:contains('info')").click(),76==a.keyCode&&jq("a.c_ab:contains('labels')").click(),84==a.keyCode&&jq("a.c_ab:contains('tools')").click())});function myTrim(a){return a.replace(/^\s+|\s+$/gm,"")}
function updH(){var a=jq("input#line");a.attr("size",Hcols);a=a.width();wo=jq("#bar").width();jq("textarea#hex").width(a);var b=jq("textarea#off");b.width(wo);jq("textarea").each(function(){jq(this).attr("rows",Hrows)});for(var c="",d=0;d<Hrows;d++){for(var e=(d*Hcols/2).toString(16);4>e.length;)e="0"+e;c=c+e+":"}b.val(c);b=jq("#yaml");a+=wo;b.width(a)}function expandA(a,b){var c=jq("> ul > li > pre",a);0<b&&c.each(function(){expandYaml(this.parentNode,1);expandA(this.parentNode,b-1)})}
function getD(a){var b=0;jq("> ul > li > pre",a).each(function(){var a=1+getD(this.parentNode);b=b>a?b:a});return b}function idName(a){return a=a.replace(/[+-.]/g,"_")}function getIdName(a){return a=a.slice(2,a.length)}function getO(a,b){if(b){var c=a.split("."),d=b;jq.each(c,function(a,b){d=d[b]?d[b]:null});return d}}
function addI(a){var b=jq("#info td"),c="";if(a){b.text("");for(var d=["id","name","version","date"];v=d.shift();){var e=getO(v,a);e&&(c=c+"<i><b>"+v+":</b> "+e+"</i>\n")}if(a.tags.owners)for(d=a.tags.owners.split(" "),c+="<i><b>owners:</b></i>\n";v=d.shift();)e=labels[v]||"-",c=c+"<i>  <b>"+v+":</b> "+e+"</i>\n";b.append("<pre>"+c+"</pre>");if(a.tools){jq("#tools").text("");d=a.tools.split(" ");for(c="<i><b>tools:</b> ";v=d.shift();)c=c+" <a>"+v+"</a>";jq("#tools").append(c);jq("#tools a").click(function(){atool(this)});
jq("#tools a:first").addClass("c_b");jq("#tool").show();jq("a.c_ab:contains('tools')").addClass("c_b");updH()}else jq("#tools").text("tools: No online tools for this module.")}}
function addP(a){if(a){prots.push(a);var b="";a.name&&(b=' Title="'+a.name+'"');var c="c_pr";a.tags&&jq.each(a.tags,function(a,b){c=c+" "+idName(b);ts=b.split(" ");gtags[a]||(gtags[a]={});jq.each(ts,function(b,c){gtags[a][c]?gtags[a][c]++:gtags[a][c]=1})});var d="",e=a.tags.owners||"?",f=a.tags.locations;f?(25<e.length+f.length&&(d=' Title="Owners: '+e+'"',e=e.substr(0,25-f.length)+"&hellip;"),f=f.replace(/ /g,"&nbsp;"),f="<i class=c_pl title='Location'>"+f+"</i>"):f="";var k=a.tags.base||"",h="",
g=a.tags.functions||"-";25<g.length&&(h=' Title="Functions: '+g+'"');var m=a.d||"?",n=a.n||"?",p=a.v||"?",q=a.messages||"____?____";a='<pre id="p_'+idName(a.id)+"\" class='"+c+"'><center class=c_pi"+b+">"+a.id+"</center><i class=c_w ><i class=c_po"+d+">"+e+"</i>"+f+"</i>\n<i>"+k+"</i>\n<i"+h+">"+g+"</i>\n<i class=c_w ><i class=c_fr ><i class=c_pd title='Deep'>"+m+"</i>.<i class=c_pn title='Nodes'>"+n+"</i>.<i class=c_pv title='Tables'>"+p+"</i>.<i class=c_pm title='Messages'>"+q+"</i></i></i></pre>";
jq("td#pr").append(a);jq("td#pr pre.c_pr:last").click(function(){ap(this)})}}
function addT(){jq.each(gtags,function(a,b){0==jq("#labels #"+a).length&&jq("#labels").append('<div id="'+a+'" />');jq("#labels #"+a).text(a+":");jq("#labels #"+a+" a").each(function(){this.outerHTML=""});var c=[];jq.each(b,function(a,b){c.push(a)});for(c=c.sort();t=c.shift();){var d="t_"+idName(t),e=labels[t],e=e?' Title="'+e+'"':"";jq("#labels #"+a).append(" <a id='"+d+"' href='#"+d+"'"+e+">"+t+"</a>");jq("#labels #"+a+" a#"+d).click(function(){at(this)})}})}
function showT(){var a=jq("td#pr pre:visible");jq("div#labels a").each(function(){var b=jq(this),c=getIdName(this.id);b.hasClass("c_b")?b.show():(b.hide(),a.each(function(){jq(this).hasClass(c)&&b.show()}))})}function at(a){jq(a).toggleClass("c_b");var b=jq("td#pr pre");b.hide();jq("div#labels a.c_b").each(function(a,d){var e=getIdName(d.id);b=b.filter("."+e)});b.show();showT()}function toggleTR(a,b){b?(jq("tr#"+a).show(),updH()):jq("tr#"+a).hide()}
function ab(a){a=jq(a);a.toggleClass("c_b");var b=a.text().substr(0,4);toggleTR(b,a.hasClass("c_b"))}function atool(a){a&&(jq("a",a.parentNode).each(function(){jq(this).removeClass("c_b")}),jq(a).addClass("c_b"))}function ap(a){jq(a);var b=jq("#pi",a);jq.each(prots,function(a,d){var e=idName(d.id),f=getIdName(b.context.id);e==f&&(prot=d)});jq("#labe").hide();jq("a.c_ab:contains('labels')").removeClass("c_b");jq("#info").show();jq("a.c_ab:contains('info')").addClass("c_b");addI(prot)}
function toggleY(a){var b=jq("ul:first",a);if(b.length){var c=jq("pre:first",a);c.toggleClass("c_on");c.hasClass("c_on")?(b.show(),(a=jq("pre:first b:first",a))&&a.text("- ")):(b.hide(),(a=jq("pre:first b:first",a))&&a.text("+ "));jq(window).resize()}return!1}
function expandYaml(a,b){var c=jq("ul:first",a);if(c.length){var d=jq("pre:first",a);b?d.addClass("c_on"):d.removeClass("c_on");d.hasClass("c_on")?(c.show(),(b=jq("pre:first b:first",a))&&b.text("- ")):(c.hide(),(b=jq("pre:first b:first",a))&&b.text("+ "));jq(window).resize()}return!1}
function initY(a){a&&(jq("#yaml").text(""),jq("#yaml").append("<div id='toolbar' >"),jq("#yaml").append(a));jq("#yaml ul").each(function(a){if(a=jq("pre:first b:first",this.parentNode))a.text("+ "),jq("pre:first",this.parentNode).addClass("c_yn")});jq("#yaml li pre").click(function(){toggleY(this.parentNode)});a=getD(jq("#yaml"));for(var b=0;b<a;b++)jq("#toolbar").append("<a id=l_"+b+" class=c_l href=#L"+b+">"+b+"</a>");expandA(jq("#yaml"),3<a?3:a);jq("a.c_l").click(function(){jq("a.c_l").each(function(){jq(this).removeClass("c_b")});
var a=getIdName(this.id),a=parseInt(a);jq("#yaml li pre").each(function(){expandYaml(this.parentNode,0)});jq(this).addClass("c_b");expandA(jq("#yaml"),a)})};
