var jq=$.noConflict(),gtags={},prot,prots=[],labels={},expand=2;
jq(document).ready(function(){jq.get("./.tags.csv",function(a){for(a=a.split("\n");l=a.shift();)8<l.length&&(v=l.split(";"),v[0]&&v[1]&&(labels[v[0].trim()]=v[1].trim()))});jq.getJSON("./.json",function(a){jq.each(a.p,function(a,c){addPr(c)})});jq("a.c_ab").click(function(){ab(this)});initYaml();getDeep(jq("#yaml"));jq(window).resize(function(){var a=jq(window).width();jq("#yaml").width(a-30)});jq(window).resize();jq("input#submit").click(function(){jq.post("/lib/",{p:prot.path,n:jq("#tools a.c_b").text(),
I:"fromstring",N:"unpack",O:"toyaml_html",str:jq("textarea").val()},function(a,b){"success"==b&&initYaml(a)})})});jq(document).keydown(function(a){a.altKey&&(73==a.keyCode&&jq("a.c_ab:contains('info')").click(),76==a.keyCode&&jq("a.c_ab:contains('labels')").click(),84==a.keyCode&&jq("a.c_ab:contains('tools')").click())});function yExpand(a,b){var c=jq("> ul > li > pre",a);0<b&&c.each(function(){expandYaml(this.parentNode,1);yExpand(this.parentNode,b-1)})}
function getDeep(a){var b=0;jq("> ul > li > pre",a).each(function(){var a=1+getDeep(this.parentNode);b=b>a?b:a});return b}function idName(a){return a=a.replace(/[+-.]/g,"_")}function getIdName(a){return a=a.slice(2,a.length)}function getObj(a,b){if(b){var c=a.split("."),d=b;jq.each(c,function(a,b){d=d[b]?d[b]:null});return d}}
function addInfo(a){var b=jq("#info td"),c="";if(a){b.text("");for(var d=["id","name","version","date"];v=d.shift();){var e=getObj(v,a);e&&(c=c+"<i><b>"+v+":</b> "+e+"</i>\n")}if(a.tags.owners)for(d=a.tags.owners.split(" "),c+="<i><b>owners:</b></i>\n";v=d.shift();)e=labels[v]||"-",c=c+"<i>  <b>"+v+":</b> "+e+"</i>\n";b.append("<pre>"+c+"</pre>");if(a.tools){jq("#tools").text("");d=a.tools.split(" ");for(c="<i><b>tools:</b> ";v=d.shift();)c=c+" <a>"+v+"</a>";jq("#tools").append(c);jq("#tools a").click(function(){atool(this)});
jq("#tools a:first").addClass("c_b");jq("#tool").show();jq("a.c_ab:contains('tools')").addClass("c_b")}else jq("#tools").text("tools: No any tools for this module.")}}
function addPr(a){if(a){prots.push(a);var b="";a.name&&(b=' Title="'+a.name+'"');var c="c_pr";a.tags&&jq.each(a.tags,function(a,b){c=c+" "+idName(b);ts=b.split(" ");gtags[a]||(gtags[a]={});jq.each(ts,function(b,c){gtags[a][c]?gtags[a][c]++:gtags[a][c]=1})});var d="",e=a.tags.owners||"?",f=a.tags.locations;f?(25<e.length+f.length&&(d=' Title="Owners: '+e+'"',e=e.substr(0,25-f.length)+"&hellip;"),f=f.replace(/ /g,"&nbsp;"),f="<i class=c_pl title='Location'>"+f+"</i>"):f="";var k=a.tags.base||"",h="",
g=a.tags.functions||"-";25<g.length&&(h=' Title="Functions: '+g+'"');var m=a.d||"?",n=a.n||"?",p=a.v||"?",q=a.messages||"____?____";a='<pre id="p_'+idName(a.id)+"\" class='"+c+"'><center class=c_pi"+b+">"+a.id+"</center><i class=c_w ><i class=c_po"+d+">"+e+"</i>"+f+"</i>\n<i>"+k+"</i>\n<i"+h+">"+g+"</i>\n<i class=c_w ><i class=c_fr ><i class=c_pd title='Deep'>"+m+"</i>.<i class=c_pn title='Nodes'>"+n+"</i>.<i class=c_pv title='Tables'>"+p+"</i>.<i class=c_pm title='Messages'>"+q+"</i></i></i></pre>";
jq("td#pr").append(a);jq("td#pr pre.c_pr:last").click(function(){ap(this)});updTags()}}
function updTags(){jq.each(gtags,function(a,b){0==jq("#labels #"+a).length&&jq("#labels").append('<div id="'+a+'" />');jq("#labels #"+a).text(a+":");jq("#labels #"+a+" a").each(function(){this.outerHTML=""});var c=[];jq.each(b,function(a,b){c.push(a)});for(c=c.sort();t=c.shift();){var d="t_"+idName(t),e=labels[t],e=e?' Title="'+e+'"':"";jq("#labels #"+a).append(" <a id='"+d+"' href='#"+d+"'"+e+">"+t+"</a>");jq("#labels #"+a+" a#"+d).click(function(){at(this)})}})}
function showTags(){var a=jq("td#pr pre:visible");jq("div#labels a").each(function(){var b=jq(this),c=getIdName(this.id);b.hasClass("c_b")?b.show():(b.hide(),a.each(function(){jq(this).hasClass(c)&&b.show()}))})}function at(a){jq(a).toggleClass("c_b");var b=jq("td#pr pre");b.hide();jq("div#labels a.c_b").each(function(a,d){var e=getIdName(d.id);b=b.filter("."+e)});b.show();showTags()}function trToggle(a,b){b?jq("tr#"+a).show():jq("tr#"+a).hide()}
function ab(a){a=jq(a);a.toggleClass("c_b");var b=a.text().substr(0,4);trToggle(b,a.hasClass("c_b"))}function atool(a){a=jq(a);jq("a",a.parentNode).each(function(){jq(this).removeClass("c_b")});a.addClass("c_b")}
function ap(a){jq(a);var b=jq("#pi",a);jq.each(prots,function(a,d){var e=idName(d.id),f=getIdName(b.context.id);e==f&&(jq("#path").text(d.path),prot=d)});jq("#labe").hide();jq("a.c_ab:contains('labels')").removeClass("c_b");jq("#info").show();jq("a.c_ab:contains('info')").addClass("c_b");addInfo(prot)}
function toggleYaml(a){var b=jq("ul:first",a);if(b.length){var c=jq("pre:first",a);c.toggleClass("c_on");c.hasClass("c_on")?(b.show(),(a=jq("pre:first b:first",a))&&a.text("- ")):(b.hide(),(a=jq("pre:first b:first",a))&&a.text("+ "));jq(window).resize()}return!1}
function expandYaml(a,b){var c=jq("ul:first",a);if(c.length){var d=jq("pre:first",a);b?d.addClass("c_on"):d.removeClass("c_on");d.hasClass("c_on")?(c.show(),(b=jq("pre:first b:first",a))&&b.text("- ")):(c.hide(),(b=jq("pre:first b:first",a))&&b.text("+ "));jq(window).resize()}return!1}
function initYaml(a){a&&(jq("#yaml").text(""),jq("#yaml").append("<div id='toolbar' >"),jq("#yaml").append(a));jq("#yaml ul").each(function(a){if(a=jq("pre:first b:first",this.parentNode))a.text("+ "),jq("pre:first",this.parentNode).addClass("c_yn")});jq("#yaml li pre").click(function(){toggleYaml(this.parentNode)});a=getDeep(jq("#yaml"));for(var b=0;b<a;b++)jq("#toolbar").append("<a id=l_"+b+" class=c_l href=#L"+b+">"+b+"</a>");yExpand(jq("#yaml"),3<a?3:a);jq("a.c_l").click(function(){jq("a.c_l").each(function(){jq(this).removeClass("c_b")});
var a=getIdName(this.id),a=parseInt(a);jq("#yaml li pre").each(function(){expandYaml(this.parentNode,0)});jq(this).addClass("c_b");yExpand(jq("#yaml"),a)})};
